#### CUSTOM EXCEPTIONS ####
class RoboticsError(Exception): ...


class RoboticsStop(Exception): ...


class EvolverEventError(Exception): ...


class xArmError(Exception): ...


class SmartStationError(Exception): ...


class DispenseHeadError(Exception): ...


class EvolverSerialError(Exception): ...


class EvolverParameterError(Exception): ...


class HTEvolverClientError(Exception): ...


class EvolverPacketError(Exception): ...


class StationInfluxCommandError(Exception): ...


class PolarsDataStoreError(Exception): ...
