#### CUSTOM EXCEPTIONS ####
class RoboticsRoutineError(Exception): ...


class xArmError(Exception): ...


class PipetteHeadError(Exception): ...


class StopRobotics(Exception): ...


class EvolverSerialError(Exception): ...


class EvolverError(Exception): ...


class ClientError(Exception): ...


class RoboticsServerError(Exception): ...
